#! /bin/sh
systemctl --user start user-graphical.target
sxhkd &

#Restore wallpaper
wal -R &

# Desktops
bspc monitor -d              #web telegram terminal files music work
bspc config border_width	0
bspc config window_gap		0

# Monocles
bspc config gapless_monocle	true
bspc config borderless_monocle	true
bspc config single_monocle	 true

# Settings
bspc config focus_follows_pointer  true
bspc config split_ratio          0.5
bspc config focus_by_distance    true
bspc config history_aware_focus  true

# Rules
bspc rule -a Nightly desktop=^1 state=tiled
bspc rule -a Nightly:Browser state=floating
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:firefox state=floating
bspc rule -a Nightly:Prompt state=floating
bspc rule -a "TelegramDesktop" desktop=^2 
#bspc rule -a "Spotify" desktop=^5 state=tiled
bspc rule -a "TeamSpeak 3" state=pseudo-tiled desktop=^5
bspc rule -a Discord desktop=^5

# Scripts
bspc subscribe desktop_focus | while read line; do bspc node -f pointed; done & disown
